package com.mainproject.view.admin;

import com.mainproject.dao.OrderDAO;import com.mainproject.dao.ProductDAO;import com.mainproject.dao.UserDAO;import com.mainproject.model.Order;import com.mainproject.model.Product;import com.mainproject.model.User;import javafx.collections.FXCollections;import javafx.geometry.Insets;import javafx.scene.chart.*;import javafx.scene.control.*;import javafx.scene.layout.*;import javafx.stage.Stage;import java.util.*;
public class AnalyticsReports{
 private final Stage stage;private final AdminDashboard dashboard;private final UserDAO users=new UserDAO();private final ProductDAO products=new ProductDAO();private final OrderDAO orders=new OrderDAO();private BorderPane root;private VBox content;
 public AnalyticsReports(Stage s,AdminDashboard d){stage=s;dashboard=d;}public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"Analytics & Reports"));root.setTop(AdminCommon.topBar("Analytics & Reports",()->AdminCommon.collapse(root),this::load));content=new VBox(15);content.setPadding(new Insets(20));root.setCenter(new ScrollPane(content));stage.getScene().setRoot(root);load();}
 private void load(){content.getChildren().clear();List<User>us=users.getAllUsers();List<Product>ps=products.getAllProducts();List<Order>os=orders.getAllOrders();long farmers=us.stream().filter(u->"Farmer".equalsIgnoreCase(u.getRole())).count();long buyers=us.stream().filter(u->"Buyer".equalsIgnoreCase(u.getRole())).count();double revenue=os.stream().mapToDouble(Order::getTotalAmount).sum();GridPane cards=new GridPane();cards.setHgap(12);cards.setVgap(12);cards.add(card("Users",us.size()),0,0);cards.add(card("Farmers",farmers),1,0);cards.add(card("Buyers",buyers),2,0);cards.add(card("Products",ps.size()),3,0);cards.add(card("Orders",os.size()),0,1);cards.add(card("Revenue","₹"+String.format("%.2f",revenue)),1,1);CategoryAxis x=new CategoryAxis();NumberAxis y=new NumberAxis();LineChart<String,Number> chart=new LineChart<>(x,y);chart.setTitle("Order Revenue by Status");XYChart.Series<String,Number> series=new XYChart.Series<>();Map<String,Double> by=new LinkedHashMap<>();for(Order o:os)by.merge(AdminCommon.s(o.getStatus()),o.getTotalAmount(),Double::sum);for(Map.Entry<String,Double>e:by.entrySet())series.getData().add(new XYChart.Data<>(e.getKey(),e.getValue()));chart.getData().add(series);content.getChildren().addAll(cards,chart);}
 private VBox card(String n,Object v){VBox b=new VBox(5,new Label(n),new Label(AdminCommon.s(v)));b.setPadding(new Insets(15));AdminCommon.card(b);return b;}
}
