package com.mainproject.view.admin;

import com.mainproject.dao.AdminFirestoreDAO;import javafx.collections.FXCollections;import javafx.collections.ObservableList;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.control.cell.PropertyValueFactory;import javafx.scene.layout.*;import javafx.stage.Stage;import java.util.*;
public class AuditLogs{
 private final Stage stage;private final AdminDashboard dashboard;private final AdminFirestoreDAO dao=new AdminFirestoreDAO();private BorderPane root;private TableView<Row>table;private ObservableList<Row>data=FXCollections.observableArrayList();private TextField search;
 public AuditLogs(Stage s,AdminDashboard d){stage=s;dashboard=d;}public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"Audit Logs"));root.setTop(AdminCommon.topBar("Audit Logs",()->AdminCommon.collapse(root),this::load));root.setCenter(content());stage.getScene().setRoot(root);load();}
 private VBox content(){VBox b=new VBox(10);b.setPadding(new Insets(20));search=new TextField();search.setPromptText("Search admin, action, module, record...");search.textProperty().addListener((o,a,n)->filter());table=new TableView<>();table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("Time","time"),col("Admin","admin"),col("Action","action"),col("Module","module"),col("Record","recordId"));VBox card=new VBox(10,search,table);card.setPadding(new Insets(18));AdminCommon.card(card);b.getChildren().add(card);return b;}
 private <T>TableColumn<Row,T>col(String h,String p){TableColumn<Row,T>c=new TableColumn<>(h);c.setCellValueFactory(new PropertyValueFactory<>(p));return c;}private void load(){data.clear();for(Map<String,Object>m:dao.getAll("adminAuditLogs"))data.add(Row.of(m));filter();}private void filter(){if(table==null)return;String q=search.getText().trim().toLowerCase();ObservableList<Row>x=FXCollections.observableArrayList();for(Row r:data)if(q.isEmpty()||r.admin.toLowerCase().contains(q)||r.action.toLowerCase().contains(q)||r.module.toLowerCase().contains(q)||r.recordId.toLowerCase().contains(q))x.add(r);table.setItems(x);}static class Row{String time,admin,action,module,recordId;static Row of(Map<String,Object>m){Row r=new Row();r.time=AdminCommon.s(m.get("createdAt"));r.admin=AdminCommon.s(m.get("admin"));r.action=AdminCommon.s(m.get("action"));r.module=AdminCommon.s(m.get("module"));r.recordId=AdminCommon.s(m.get("recordId"));return r;}public String getTime(){return time;}public String getAdmin(){return admin;}public String getAction(){return action;}public String getModule(){return module;}public String getRecordId(){return recordId;}}
}
