package com.mainproject.view.admin;

import com.mainproject.controller.EquipmentController;import com.mainproject.model.Equipment;import javafx.collections.FXCollections;import javafx.collections.ObservableList;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.control.cell.PropertyValueFactory;import javafx.scene.layout.*;import javafx.stage.Stage;import java.util.*;
public class EquipmentManagement{
 private final Stage stage;private final AdminDashboard dashboard;private final EquipmentController controller=new EquipmentController();private BorderPane root;private TableView<Equipment>table;private ObservableList<Equipment>data=FXCollections.observableArrayList();private String filter="All";private TextField search;
 public EquipmentManagement(Stage s,AdminDashboard d){stage=s;dashboard=d;}public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"Equipment Management"));root.setTop(AdminCommon.topBar("Equipment Management",()->AdminCommon.collapse(root),this::load));root.setCenter(content());stage.getScene().setRoot(root);load();}
 private VBox content(){VBox b=new VBox(12);b.setPadding(new Insets(20));HBox tools=new HBox(8);search=new TextField();search.setPromptText("Search equipment or owner...");search.textProperty().addListener((o,a,n)->refresh());ComboBox<String>tabs=new ComboBox<>(FXCollections.observableArrayList("All","Pending","Approved","Rejected"));tabs.setValue("All");tabs.setOnAction(e->{filter=tabs.getValue();refresh();});Button add=new Button("+ Add Equipment");add.setOnAction(e->add());tools.getChildren().addAll(search,tabs,add);table=new TableView<>();table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("Equipment","name"),col("Owner","ownerName"),col("Category","category"),col("Price/Day","price"),col("Location","location"),col("Status","status"));TableColumn<Equipment,Void>a=new TableColumn<>("Action");a.setCellFactory(c->new TableCell<>(){Button v=new Button("View"),e=new Button("Edit"),s=new Button("Status"),del=new Button("Delete");HBox box=new HBox(5,v,e,s,del);{v.setOnAction(x->view(getTableRow().getItem()));e.setOnAction(x->edit(getTableRow().getItem()));s.setOnAction(x->status(getTableRow().getItem()));del.setOnAction(x->remove(getTableRow().getItem()));}protected void updateItem(Void x,boolean empty){super.updateItem(x,empty);setGraphic(empty?null:box);}});table.getColumns().add(a);VBox card=new VBox(10,tools,table);card.setPadding(new Insets(18));AdminCommon.card(card);b.getChildren().add(card);return b;}
 private <T>TableColumn<Equipment,T>col(String h,String p){TableColumn<Equipment,T>c=new TableColumn<>(h);c.setCellValueFactory(new PropertyValueFactory<>(p));return c;}private void load(){data.setAll(controller.getAllEquipmentForAdmin());refresh();}private void refresh(){if(table==null)return;String q=search==null?"":search.getText().trim().toLowerCase();ObservableList<Equipment>x=FXCollections.observableArrayList();for(Equipment e:data){String st=e.getStatus()==null?(e.isAvailable()?"Approved":"Pending"):e.getStatus();boolean sm="All".equals(filter)||st.equalsIgnoreCase(filter);boolean qm=q.isEmpty()||AdminCommon.s(e.getName()).toLowerCase().contains(q)||AdminCommon.s(e.getOwnerName()).toLowerCase().contains(q);if(sm&&qm)x.add(e);}table.setItems(x);}
 private void add(){Dialog<ButtonType>d=new Dialog<>();d.setTitle("Add Equipment");d.getDialogPane().getButtonTypes().addAll(ButtonType.OK,ButtonType.CANCEL);TextField n=new TextField(),owner=new TextField(),email=new TextField(),price=new TextField(),loc=new TextField();ComboBox<String>cat=new ComboBox<>(FXCollections.observableArrayList("Tractor","Tillage","Sowing","Irrigation","Harvesting","Other"));cat.setValue("Tractor");GridPane g=new GridPane();g.setHgap(8);g.setVgap(8);g.addRow(0,new Label("Name"),n);g.addRow(1,new Label("Owner"),owner);g.addRow(2,new Label("Owner Email"),email);g.addRow(3,new Label("Category"),cat);g.addRow(4,new Label("Price/Day"),price);g.addRow(5,new Label("Location"),loc);d.getDialogPane().setContent(g);if(d.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK){try{Equipment e=new Equipment(n.getText().trim(),Double.parseDouble(price.getText().trim()),loc.getText().trim(),cat.getValue(),"",true,email.getText().trim(),owner.getText().trim(),"");e.setStatus("Pending");if(controller.addEquipment(e))load();}catch(Exception x){AdminCommon.error("Invalid Data","Price must be numeric.");}}}
 private void view(Equipment e){if(e!=null)AdminCommon.info("Equipment Details","Name: "+e.getName()+"\nOwner: "+e.getOwnerName()+"\nCategory: "+e.getCategory()+"\nPrice/Day: "+e.getPrice()+"\nLocation: "+e.getLocation()+"\nStatus: "+AdminCommon.s(e.getStatus()));}
 private void edit(Equipment e){if(e==null)return;Dialog<ButtonType>d=new Dialog<>();d.getDialogPane().getButtonTypes().addAll(ButtonType.OK,ButtonType.CANCEL);TextField n=new TextField(e.getName()),price=new TextField(String.valueOf(e.getPrice())),loc=new TextField(e.getLocation());GridPane g=new GridPane();g.setHgap(8);g.setVgap(8);g.addRow(0,new Label("Name"),n);g.addRow(1,new Label("Price/Day"),price);g.addRow(2,new Label("Location"),loc);d.getDialogPane().setContent(g);if(d.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK){try{e.setName(n.getText().trim());e.setPrice(Double.parseDouble(price.getText().trim()));e.setLocation(loc.getText().trim());if(controller.updateEquipment(e))load();}catch(Exception x){AdminCommon.error("Invalid Data","Price must be numeric.");}}}
 private void status(Equipment e){if(e==null)return;ChoiceDialog<String>d=new ChoiceDialog<>(e.getStatus()==null?"Pending":e.getStatus(),"Pending","Approved","Rejected");d.showAndWait().ifPresent(s->{e.setStatus(s);e.setAvailable("Approved".equals(s));if(controller.updateEquipment(e))load();});}private void remove(Equipment e){if(e!=null&&AdminCommon.confirm("Delete Equipment","Delete "+e.getName()+"?")){if(controller.deleteEquipment(e.getEquipmentId()))load();}}
}
