package com.mainproject.view.admin;

import com.mainproject.dao.AdminFirestoreDAO;import javafx.collections.FXCollections;import javafx.collections.ObservableList;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.control.cell.PropertyValueFactory;import javafx.scene.layout.*;import javafx.stage.Stage;import java.util.*;
public class FeedbackReviews{
 private final Stage stage;private final AdminDashboard dashboard;private final AdminFirestoreDAO dao=new AdminFirestoreDAO();private BorderPane root;private TableView<Row> table;private ObservableList<Row>data=FXCollections.observableArrayList();private TextField search;private String type="All";
 public FeedbackReviews(Stage s,AdminDashboard d){stage=s;dashboard=d;}public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"Feedback & Reviews"));root.setTop(AdminCommon.topBar("Feedback & Reviews",()->AdminCommon.collapse(root),this::load));root.setCenter(content());stage.getScene().setRoot(root);load();}
 private VBox content(){VBox b=new VBox(12);b.setPadding(new Insets(20));HBox tabs=new HBox(6);for(String t:new String[]{"All","Product","Farmer"}){Button x=new Button(t);x.setOnAction(e->{type=t;filter();});tabs.getChildren().add(x);}search=new TextField();search.setPromptText("Search feedback...");search.textProperty().addListener((o,a,n)->filter());table=new TableView<>();table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("User","user"),col("Type","type"),col("Rating","rating"),col("Comment","comment"),col("Status","status"));TableColumn<Row,Void>a=new TableColumn<>("Action");a.setCellFactory(c->new TableCell<>(){Button v=new Button("Moderate");{v.setOnAction(e->moderate(getTableRow().getItem()));}protected void updateItem(Void x,boolean empty){super.updateItem(x,empty);setGraphic(empty?null:v);}});table.getColumns().add(a);VBox card=new VBox(10,tabs,search,table);card.setPadding(new Insets(18));AdminCommon.card(card);b.getChildren().add(card);return b;}
 private <T>TableColumn<Row,T>col(String h,String p){TableColumn<Row,T>c=new TableColumn<>(h);c.setCellValueFactory(new PropertyValueFactory<>(p));return c;}private void load(){data.clear();for(Map<String,Object>m:dao.getAll("adminFeedback"))data.add(Row.of(m));filter();}private void filter(){if(table==null)return;String q=search==null?"":search.getText().trim().toLowerCase();ObservableList<Row>x=FXCollections.observableArrayList();for(Row r:data)if(("All".equals(type)||r.type.equalsIgnoreCase(type))&&(q.isEmpty()||r.user.toLowerCase().contains(q)||r.comment.toLowerCase().contains(q)))x.add(r);table.setItems(x);}private void moderate(Row r){if(r==null)return;ChoiceDialog<String>d=new ChoiceDialog<>(r.status,"Approved","Pending","Under Review","Rejected");d.setTitle("Moderate Feedback");d.setHeaderText(r.user);d.showAndWait().ifPresent(ns->{Map<String,Object>m=new HashMap<>();m.put("status",ns);dao.update("adminFeedback",r.id,m);dao.audit("Super Admin","Moderated Feedback","Feedback & Reviews",r.id);load();});}
 static class Row{String id,user,type,rating,comment,status;static Row of(Map<String,Object>m){Row r=new Row();r.id=AdminCommon.s(m.get("_id"));r.user=AdminCommon.s(m.get("user"));r.type=AdminCommon.s(m.get("type"));r.rating=AdminCommon.s(m.get("rating"));r.comment=AdminCommon.s(m.get("comment"));r.status=AdminCommon.s(m.get("status"));if(r.status.isBlank())r.status="Pending";return r;}public String getUser(){return user;}public String getType(){return type;}public String getRating(){return rating;}public String getComment(){return comment;}public String getStatus(){return status;}}
}
