package com.mainproject.view.admin;

import com.mainproject.dao.AdminFirestoreDAO;import javafx.collections.FXCollections;import javafx.collections.ObservableList;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.control.cell.PropertyValueFactory;import javafx.scene.layout.*;import javafx.stage.Stage;import java.util.*;
public class LiveMarketplace{
 private final Stage stage;private final AdminDashboard dashboard;private final AdminFirestoreDAO dao=new AdminFirestoreDAO();private BorderPane root;private TableView<Row>table;private ObservableList<Row>data=FXCollections.observableArrayList();private String filter="All";
 public LiveMarketplace(Stage s,AdminDashboard d){stage=s;dashboard=d;}public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"Live Marketplace"));root.setTop(AdminCommon.topBar("Live Marketplace",()->AdminCommon.collapse(root),this::load));root.setCenter(content());stage.getScene().setRoot(root);load();}
 private VBox content(){VBox b=new VBox(12);b.setPadding(new Insets(20));HBox tabs=new HBox(6);for(String x:new String[]{"All","Live Now","Upcoming","Ended","Reported"}){Button bt=new Button(x);bt.setOnAction(e->{filter=x;refresh();});tabs.getChildren().add(bt);}Button add=new Button("+ Start Live Session");add.setOnAction(e->add());HBox tools=new HBox(8,tabs,add);table=new TableView<>();table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("Title","title"),col("Farmer","farmer"),col("Started","started"),col("Viewers","viewers"),col("Status","status"));TableColumn<Row,Void>a=new TableColumn<>("Action");a.setCellFactory(c->new TableCell<>(){Button v=new Button("Manage");{v.setOnAction(e->manage(getTableRow().getItem()));}protected void updateItem(Void x,boolean empty){super.updateItem(x,empty);setGraphic(empty?null:v);}});table.getColumns().add(a);VBox card=new VBox(10,tools,table);card.setPadding(new Insets(18));AdminCommon.card(card);b.getChildren().add(card);return b;}
 private <T>TableColumn<Row,T>col(String h,String p){TableColumn<Row,T>c=new TableColumn<>(h);c.setCellValueFactory(new PropertyValueFactory<>(p));return c;}private void load(){data.clear();for(Map<String,Object>m:dao.getAll("adminLiveStreams"))data.add(Row.of(m));refresh();}private void refresh(){ObservableList<Row>x=FXCollections.observableArrayList();for(Row r:data)if("All".equals(filter)||filter.equals(r.status))x.add(r);table.setItems(x);}private void add(){TextInputDialog d=new TextInputDialog();d.setTitle("Start Live Session");d.setHeaderText("Enter session title");d.showAndWait().ifPresent(t->{if(t.isBlank())return;Map<String,Object>m=new HashMap<>();m.put("title",t.trim());m.put("farmer","Admin-created");m.put("started",new Date().toString());m.put("viewers",0L);m.put("status","Live Now");String id=dao.create("adminLiveStreams",m);dao.audit("Super Admin","Started Live Session","Live Marketplace",id);load();});}private void manage(Row r){if(r==null)return;ChoiceDialog<String>d=new ChoiceDialog<>(r.status,"Live Now","Upcoming","Ended","Reported");d.setTitle("Manage Live Session");d.showAndWait().ifPresent(ns->{Map<String,Object>m=new HashMap<>();m.put("status",ns);dao.update("adminLiveStreams",r.id,m);dao.audit("Super Admin","Updated Live Session","Live Marketplace",r.id);load();});}
 static class Row{String id,title,farmer,started,status;String viewers;static Row of(Map<String,Object>m){Row r=new Row();r.id=AdminCommon.s(m.get("_id"));r.title=AdminCommon.s(m.get("title"));r.farmer=AdminCommon.s(m.get("farmer"));r.started=AdminCommon.s(m.get("started"));r.viewers=AdminCommon.s(m.get("viewers"));r.status=AdminCommon.s(m.get("status"));if(r.status.isBlank())r.status="Upcoming";return r;}public String getTitle(){return title;}public String getFarmer(){return farmer;}public String getStarted(){return started;}public String getViewers(){return viewers;}public String getStatus(){return status;}}
}
