package com.mainproject.view.admin;

import com.mainproject.controller.NotificationController;import com.mainproject.controller.UserController;import com.mainproject.model.Notification;import com.mainproject.model.User;import javafx.collections.FXCollections;import javafx.collections.ObservableList;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.control.cell.PropertyValueFactory;import javafx.scene.layout.*;import javafx.stage.Stage;import java.util.*;
public class NotificationManagement{
 private final Stage stage;private final AdminDashboard dashboard;private final NotificationController controller=new NotificationController();private final UserController users=new UserController();private BorderPane root;private TableView<Row>table;private ObservableList<Row>data=FXCollections.observableArrayList();private ComboBox<String>audience,type;private TextArea message;
 public NotificationManagement(Stage s,AdminDashboard d){stage=s;dashboard=d;}public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"Notifications"));root.setTop(AdminCommon.topBar("Notification Management",()->AdminCommon.collapse(root),this::load));root.setCenter(buildContent());stage.getScene().setRoot(root);load();}
 private HBox buildContent(){VBox send=new VBox(8);send.setPadding(new Insets(15));AdminCommon.card(send);audience=new ComboBox<>(FXCollections.observableArrayList("All Users","Farmers","Buyers","Specific Email"));audience.setValue("All Users");type=new ComboBox<>(FXCollections.observableArrayList("General","Order","Approval","Alert"));type.setValue("General");message=new TextArea();message.setPromptText("Notification message");Button sendBtn=new Button("Send Notification");sendBtn.setStyle("-fx-background-color:"+AdminCommon.GREEN+";-fx-text-fill:white;");sendBtn.setOnAction(e->send());send.getChildren().addAll(new Label("Audience"),audience,type,message,sendBtn);VBox right=new VBox(10);table=new TableView<>();table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("Title","title"),col("User","user"),col("Type","type"),col("Date","date"),col("Read","read"));right.getChildren().add(table);HBox row=new HBox(15,send,right);HBox.setHgrow(right,Priority.ALWAYS);return row;}
 private <T>TableColumn<Row,T>col(String h,String p){TableColumn<Row,T>c=new TableColumn<>(h);c.setCellValueFactory(new PropertyValueFactory<>(p));return c;}private void load(){data.clear();for(Notification n:controller.getAllNotifications())data.add(new Row(n));table.setItems(data);}private void send(){String msg=message.getText().trim();if(msg.isBlank()){AdminCommon.error("Missing Message","Enter a notification message.");return;}List<String>targets=new ArrayList<>();String a=audience.getValue();if("Specific Email".equals(a)){TextInputDialog d=new TextInputDialog();d.setHeaderText("Recipient email");d.showAndWait().ifPresent(targets::add);}else{for(User u:users.getAllUsers())if("All Users".equals(a)||("Farmers".equals(a)&&"Farmer".equalsIgnoreCase(u.getRole()))||("Buyers".equals(a)&&"Buyer".equalsIgnoreCase(u.getRole())))targets.add(u.getEmail());}int sent=0;for(String email:targets){if(email==null||email.isBlank())continue;Notification n=new Notification(email,type.getValue(),msg,type.getValue());if(controller.addNotification(n))sent++;}message.clear();load();AdminCommon.info("Notifications","Sent to "+sent+" user(s).");}
 static class Row{String title,user,type,date,read;Row(Notification n){title=AdminCommon.s(n.getTitle());user=AdminCommon.s(n.getUserEmail());type=AdminCommon.s(n.getType());date=AdminCommon.s(n.getCreatedAt());read=String.valueOf(n.isRead());}public String getTitle(){return title;}public String getUser(){return user;}public String getType(){return type;}public String getDate(){return date;}public String getRead(){return read;}}
}
