package com.mainproject.view.admin;

import com.mainproject.dao.OrderDAO;import com.mainproject.model.Order;import javafx.collections.FXCollections;import javafx.collections.ObservableList;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.control.cell.PropertyValueFactory;import javafx.scene.layout.*;import javafx.stage.Stage;import java.util.*;
public class OrderManagement{
 private final Stage stage;private final AdminDashboard dashboard;private final OrderDAO controller=new OrderDAO();private BorderPane root;private TableView<Order>table;private ObservableList<Order>data=FXCollections.observableArrayList();private TextField search;private String filter="All";
 public OrderManagement(Stage s,AdminDashboard d){stage=s;dashboard=d;}public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"Order Management"));root.setTop(AdminCommon.topBar("Order Management",()->AdminCommon.collapse(root),this::load));root.setCenter(content());stage.getScene().setRoot(root);load();}
 private VBox content(){VBox b=new VBox(12);b.setPadding(new Insets(20));HBox tools=new HBox(8);search=new TextField();search.setPromptText("Search order or buyer...");search.textProperty().addListener((o,a,n)->refresh());ComboBox<String>tabs=new ComboBox<>(FXCollections.observableArrayList("All","Pending","Processing","Shipped","Delivered","Cancelled"));tabs.setValue("All");tabs.setOnAction(e->{filter=tabs.getValue();refresh();});tools.getChildren().addAll(search,tabs);table=new TableView<>();table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("Order ID","orderId"),col("Buyer","buyerName"),col("Payment","paymentMethod"),col("Total","totalAmount"),col("Status","status"),col("Date","orderDate"));TableColumn<Order,Void>a=new TableColumn<>("Action");a.setCellFactory(c->new TableCell<>(){Button v=new Button("View"),s=new Button("Status");HBox box=new HBox(5,v,s);{v.setOnAction(e->view(getTableRow().getItem()));s.setOnAction(e->status(getTableRow().getItem()));}protected void updateItem(Void x,boolean empty){super.updateItem(x,empty);setGraphic(empty?null:box);}});table.getColumns().add(a);VBox card=new VBox(10,tools,table);card.setPadding(new Insets(18));AdminCommon.card(card);b.getChildren().add(card);return b;}
 private <T>TableColumn<Order,T>col(String h,String p){TableColumn<Order,T>c=new TableColumn<>(h);c.setCellValueFactory(new PropertyValueFactory<>(p));return c;}private void load(){data.setAll(controller.getAllOrders());refresh();}private void refresh(){if(table==null)return;String q=search==null?"":search.getText().trim().toLowerCase();ObservableList<Order>x=FXCollections.observableArrayList();for(Order o:data){boolean sf="All".equals(filter)||AdminCommon.s(o.getStatus()).equalsIgnoreCase(filter);boolean sq=q.isEmpty()||AdminCommon.s(o.getOrderId()).toLowerCase().contains(q)||AdminCommon.s(o.getBuyerName()).toLowerCase().contains(q)||AdminCommon.s(o.getBuyerEmail()).toLowerCase().contains(q);if(sf&&sq)x.add(o);}table.setItems(x);}private void view(Order o){if(o!=null)AdminCommon.info("Order Details","Order: "+o.getOrderId()+"\nBuyer: "+o.getBuyerName()+"\nPayment: "+o.getPaymentMethod()+"\nSubtotal: ₹"+o.getSubtotal()+"\nDelivery: ₹"+o.getDeliveryCharge()+"\nTotal: ₹"+o.getTotalAmount()+"\nStatus: "+o.getStatus()+"\nAddress: "+o.getDeliveryAddress());}private void status(Order o){if(o==null)return;ChoiceDialog<String>d=new ChoiceDialog<>(o.getStatus(),"Pending","Processing","Shipped","Delivered","Cancelled");d.showAndWait().ifPresent(s->{if(controller.updateStatus(o.getOrderId(),s))load();});}
}
