package com.mainproject.view.admin;

import com.mainproject.dao.AdminFirestoreDAO;import com.mainproject.dao.OrderDAO;import com.mainproject.model.Order;import javafx.collections.FXCollections;import javafx.collections.ObservableList;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.control.cell.PropertyValueFactory;import javafx.scene.layout.*;import javafx.stage.Stage;import java.text.DecimalFormat;import java.time.LocalDate;import java.util.*;
public class PaymentManagement{
 private final Stage stage;private final AdminDashboard dashboard;private final OrderDAO orders=new OrderDAO();private final AdminFirestoreDAO dao=new AdminFirestoreDAO();private BorderPane root;private TableView<Row>table;private ObservableList<Row>data=FXCollections.observableArrayList();private TextField search;
 public PaymentManagement(Stage s,AdminDashboard d){stage=s;dashboard=d;}public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"Payment Management"));root.setTop(AdminCommon.topBar("Payment Management",()->AdminCommon.collapse(root),this::load));root.setCenter(content());stage.getScene().setRoot(root);load();}
 private VBox content(){VBox b=new VBox(12);b.setPadding(new Insets(20));search=new TextField();search.setPromptText("Search order, buyer, payment method...");search.textProperty().addListener((o,a,n)->filter());table=new TableView<>();table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("Order ID","orderId"),col("Buyer","buyer"),col("Amount","amount"),col("Method","method"),col("Status","status"),col("Date","date"));Label note=new Label("Payments are derived from the existing orders collection so no fake transactions are shown.");note.setStyle("-fx-text-fill:#777;");VBox card=new VBox(10,search,table,note);card.setPadding(new Insets(18));AdminCommon.card(card);b.getChildren().add(card);return b;}
 private <T>TableColumn<Row,T>col(String h,String p){TableColumn<Row,T>c=new TableColumn<>(h);c.setCellValueFactory(new PropertyValueFactory<>(p));return c;}private void load(){data.clear();try{List<Order> list=orders.getAllOrders();for(Order o:list){if(o==null)continue;data.add(new Row(o));}}catch(Exception e){AdminCommon.error("Payment Load Failed",e.getMessage());}filter();}private void filter(){if(table==null)return;String q=search.getText().trim().toLowerCase();ObservableList<Row>x=FXCollections.observableArrayList();for(Row r:data)if(q.isEmpty()||r.orderId.toLowerCase().contains(q)||r.buyer.toLowerCase().contains(q)||r.method.toLowerCase().contains(q))x.add(r);table.setItems(x);}static class Row{String orderId,buyer,amount,method,status,date;Row(Order o){orderId=AdminCommon.s(o.getOrderId());buyer=AdminCommon.s(o.getBuyerName());amount="₹"+new DecimalFormat("0.00").format(o.getTotalAmount());method=AdminCommon.s(o.getPaymentMethod());status=AdminCommon.s(o.getStatus());date=o.getOrderDate()==null?"":o.getOrderDate().toString();}public String getOrderId(){return orderId;}public String getBuyer(){return buyer;}public String getAmount(){return amount;}public String getMethod(){return method;}public String getStatus(){return status;}public String getDate(){return date;}}
}
