package com.mainproject.view.admin;

import com.mainproject.controller.ProductController;import com.mainproject.controller.UserController;import com.mainproject.model.Product;import com.mainproject.model.User;import javafx.collections.FXCollections;import javafx.collections.ObservableList;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.control.cell.PropertyValueFactory;import javafx.scene.layout.*;import javafx.stage.Stage;import java.util.*;
public class ProductManagement{
 private final Stage stage;private final AdminDashboard dashboard;private final ProductController controller=new ProductController();private final UserController users=new UserController();private BorderPane root;private TableView<Product>table;private ObservableList<Product>data=FXCollections.observableArrayList();private TextField search;private String filter="All Products";
 public ProductManagement(Stage s,AdminDashboard d){stage=s;dashboard=d;}public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"Product Management"));root.setTop(AdminCommon.topBar("Product Management",()->AdminCommon.collapse(root),this::load));root.setCenter(content());stage.getScene().setRoot(root);load();}
 private VBox content(){VBox b=new VBox(12);b.setPadding(new Insets(20));HBox tools=new HBox(8);search=new TextField();search.setPromptText("Search product or farmer...");search.textProperty().addListener((o,a,n)->refresh());ComboBox<String>tabs=new ComboBox<>(FXCollections.observableArrayList("All Products","Pending","Approved","Rejected"));tabs.setValue("All Products");tabs.setOnAction(e->{filter=tabs.getValue();refresh();});Button add=new Button("+ Add Product");add.setOnAction(e->add());Button refresh=new Button("Refresh");refresh.setOnAction(e->load());tools.getChildren().addAll(search,tabs,add,refresh);table=new TableView<>();table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("Product","name"),col("Farmer","farmerEmail"),col("Category","category"),col("Price","price"),col("Stock","stock"),col("Status","status"));TableColumn<Product,Void>a=new TableColumn<>("Action");a.setCellFactory(c->new TableCell<>(){Button v=new Button("View"),e=new Button("Edit"),s=new Button("Status"),del=new Button("Delete");HBox box=new HBox(5,v,e,s,del);{v.setOnAction(x->view(getTableRow().getItem()));e.setOnAction(x->edit(getTableRow().getItem()));s.setOnAction(x->status(getTableRow().getItem()));del.setOnAction(x->remove(getTableRow().getItem()));}protected void updateItem(Void x,boolean empty){super.updateItem(x,empty);setGraphic(empty?null:box);}});table.getColumns().add(a);VBox card=new VBox(10,tools,table);card.setPadding(new Insets(18));AdminCommon.card(card);b.getChildren().add(card);return b;}
 private <T>TableColumn<Product,T>col(String h,String p){TableColumn<Product,T>c=new TableColumn<>(h);c.setCellValueFactory(new PropertyValueFactory<>(p));return c;}
 private void load(){data.setAll(controller.getAllProducts());refresh();}private void refresh(){if(table==null)return;String q=search==null?"":search.getText().trim().toLowerCase();ObservableList<Product>x=FXCollections.observableArrayList();for(Product p:data)if(("All Products".equals(filter)||AdminCommon.s(p.getStatus()).equalsIgnoreCase(filter))&&(q.isEmpty()||AdminCommon.s(p.getName()).toLowerCase().contains(q)||AdminCommon.s(p.getFarmerEmail()).toLowerCase().contains(q)))x.add(p);table.setItems(x);}
 private void add(){Dialog<ButtonType>d=new Dialog<>();d.setTitle("Add Product");d.getDialogPane().getButtonTypes().addAll(ButtonType.OK,ButtonType.CANCEL);TextField farmer=new TextField(),name=new TextField(),unit=new TextField("kg"),price=new TextField(),stock=new TextField();ComboBox<String>cat=new ComboBox<>(FXCollections.observableArrayList("Vegetables","Fruits","Grains","Other"));cat.setValue("Vegetables");GridPane g=new GridPane();g.setHgap(8);g.setVgap(8);g.addRow(0,new Label("Farmer Email"),farmer);g.addRow(1,new Label("Name"),name);g.addRow(2,new Label("Unit"),unit);g.addRow(3,new Label("Category"),cat);g.addRow(4,new Label("Price"),price);g.addRow(5,new Label("Stock"),stock);d.getDialogPane().setContent(g);if(d.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK){try{double pr=Double.parseDouble(price.getText().trim()),st=Double.parseDouble(stock.getText().trim());Product p=new Product("",farmer.getText().trim(),name.getText().trim(),unit.getText().trim(),cat.getValue(),"","","",pr,st,"Pending","");if(controller.addProduct(p)){load();AdminCommon.info("Product","Product added successfully.");}else AdminCommon.error("Product","Could not add product. Check farmer email.");}catch(Exception e){AdminCommon.error("Invalid Data","Price and stock must be numeric.");}}}
 private void view(Product p){if(p!=null)AdminCommon.info("Product Details","Name: "+p.getName()+"\nFarmer: "+p.getFarmerEmail()+"\nCategory: "+p.getCategory()+"\nPrice: "+p.getPrice()+"\nStock: "+p.getStock()+"\nStatus: "+p.getStatus());}
 private void edit(Product p){if(p==null)return;Dialog<ButtonType>d=new Dialog<>();d.getDialogPane().getButtonTypes().addAll(ButtonType.OK,ButtonType.CANCEL);TextField n=new TextField(p.getName()),price=new TextField(String.valueOf(p.getPrice())),stock=new TextField(String.valueOf(p.getStock()));GridPane g=new GridPane();g.setHgap(8);g.setVgap(8);g.addRow(0,new Label("Name"),n);g.addRow(1,new Label("Price"),price);g.addRow(2,new Label("Stock"),stock);d.getDialogPane().setContent(g);if(d.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK){try{p.setName(n.getText().trim());p.setPrice(Double.parseDouble(price.getText().trim()));p.setStock(Double.parseDouble(stock.getText().trim()));if(controller.updateProduct(p)){load();}else AdminCommon.error("Update Failed","Product could not be updated.");}catch(Exception e){AdminCommon.error("Invalid Data","Price and stock must be numeric.");}}}
 private void status(Product p){if(p==null)return;ChoiceDialog<String>d=new ChoiceDialog<>(p.getStatus(),"Pending","Approved","Rejected","Inactive");d.setHeaderText("Update status");d.showAndWait().ifPresent(s->{if(controller.updateProductStatus(p.getProductId(),s)){load();}else AdminCommon.error("Update Failed","Status could not be saved.");});}
 private void remove(Product p){if(p!=null&&AdminCommon.confirm("Delete Product","Delete "+p.getName()+"?")){if(controller.deleteProduct(p.getProductId()))load();else AdminCommon.error("Delete Failed","Product could not be deleted.");}}
}
