package com.mainproject.view.admin;

import com.mainproject.dao.AdminFirestoreDAO;
import javafx.collections.FXCollections;import javafx.collections.ObservableList;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.control.cell.PropertyValueFactory;import javafx.scene.layout.*;import javafx.stage.Stage;import java.util.*;

public class ReportsComplaints {
 private final Stage stage;private final AdminDashboard dashboard;private final AdminFirestoreDAO dao=new AdminFirestoreDAO();private BorderPane root;private TableView<Row> table;private ObservableList<Row> data=FXCollections.observableArrayList();private TextField search;private String status="All";private Button all,pending,review,resolved;
 public ReportsComplaints(Stage s,AdminDashboard d){stage=s;dashboard=d;} public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"Reports & Complaints"));root.setTop(AdminCommon.topBar("Reports & Complaints",()->AdminCommon.collapse(root),this::load));root.setCenter(content());stage.getScene().setRoot(root);load();}
 private VBox content(){VBox b=new VBox(12);b.setPadding(new Insets(20));HBox tabs=new HBox(6);all=tab("All");pending=tab("Pending");review=tab("Under Review");resolved=tab("Resolved");tabs.getChildren().addAll(all,pending,review,resolved);HBox tools=new HBox(8);search=new TextField();search.setPromptText("Search report, reporter, against...");Button go=new Button("Search");go.setOnAction(e->filter());tools.getChildren().addAll(search,go);table=new TableView<>();table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("Report ID","id"),col("Reported By","reportedBy"),col("Against","against"),col("Reason","reason"),col("Date","date"),col("Status","status"));TableColumn<Row,Void> a=new TableColumn<>("Action");a.setCellFactory(c->new TableCell<>(){Button v=new Button("View");{v.setOnAction(e->view(getTableRow().getItem()));}protected void updateItem(Void x,boolean empty){super.updateItem(x,empty);setGraphic(empty?null:v);}});table.getColumns().add(a);VBox card=new VBox(10,tabs,tools,table);card.setPadding(new Insets(18));AdminCommon.card(card);b.getChildren().add(card);return b;}
 private Button tab(String s){Button b=new Button(s);b.setOnAction(e->{status=s;styleTabs();filter();});return b;}private void styleTabs(){for(Button b:new Button[]{all,pending,review,resolved})b.setStyle("All".equals(status)&&b==all||b.getText().equals(status)?"-fx-background-color:"+AdminCommon.GREEN+";-fx-text-fill:white;":"");}
 private <T>TableColumn<Row,T> col(String h,String p){TableColumn<Row,T>c=new TableColumn<>(h);c.setCellValueFactory(new PropertyValueFactory<>(p));return c;}
 private void load(){data.clear();for(Map<String,Object>m:dao.getAll("adminReports"))data.add(Row.of(m));updateCounts();filter();}
 private void updateCounts(){all.setText("All ("+data.size()+")");pending.setText("Pending ("+count("Pending")+")");review.setText("Under Review ("+count("Under Review")+")");resolved.setText("Resolved ("+count("Resolved")+")");styleTabs();}
 private int count(String s){int n=0;for(Row r:data)if(s.equals(r.status))n++;return n;}
 private void filter(){String q=search==null?"":search.getText().trim().toLowerCase();ObservableList<Row>x=FXCollections.observableArrayList();for(Row r:data){boolean sm="All".equals(status)||r.status.equals(status);boolean qm=q.isEmpty()||r.id.toLowerCase().contains(q)||r.reportedBy.toLowerCase().contains(q)||r.against.toLowerCase().contains(q)||r.reason.toLowerCase().contains(q);if(sm&&qm)x.add(r);}table.setItems(x);}
 private void view(Row r){if(r==null)return;ChoiceDialog<String>d=new ChoiceDialog<>(r.status,"Pending","Under Review","Resolved","Dismissed");d.setTitle("Update Report");d.setHeaderText(r.id+" - "+r.reason);d.setContentText("Status:");d.showAndWait().ifPresent(ns->{Map<String,Object>m=new HashMap<>();m.put("status",ns);dao.update("adminReports",r.id,m);dao.audit("Super Admin","Updated Report Status","Reports & Complaints",r.id);load();});}
 static class Row{String id,reportedBy,against,reason,date,status;static Row of(Map<String,Object>m){Row r=new Row();r.id=AdminCommon.s(m.get("_id"));r.reportedBy=AdminCommon.s(m.get("reportedBy"));r.against=AdminCommon.s(m.get("against"));r.reason=AdminCommon.s(m.get("reason"));r.date=AdminCommon.s(m.get("date"));r.status=AdminCommon.s(m.get("status"));if(r.status.isBlank())r.status="Pending";return r;}public String getId(){return id;}public String getReportedBy(){return reportedBy;}public String getAgainst(){return against;}public String getReason(){return reason;}public String getDate(){return date;}public String getStatus(){return status;}}
}
