package com.mainproject.view.admin;

import com.mainproject.config.FirebaseConfig;import com.mainproject.dao.AdminFirestoreDAO;import com.mainproject.dao.OrderDAO;import com.mainproject.dao.ProductDAO;import com.mainproject.dao.UserDAO;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.layout.*;import javafx.stage.Stage;import java.util.*;
public class SystemDataManage{
 private final Stage stage;private final AdminDashboard dashboard;private final AdminFirestoreDAO admin=new AdminFirestoreDAO();private final UserDAO users=new UserDAO();private final ProductDAO products=new ProductDAO();private final OrderDAO orders=new OrderDAO();private BorderPane root;private VBox content;
 public SystemDataManage(Stage s,AdminDashboard d){stage=s;dashboard=d;}public void show(){root=new BorderPane();root.setStyle("-fx-background-color:"+AdminCommon.BG+";");root.setLeft(AdminCommon.sidebar(stage,dashboard,"SystemDataManage"));root.setTop(AdminCommon.topBar("System & Data Management",()->AdminCommon.collapse(root),this::refresh));content=new VBox(15);content.setPadding(new Insets(20));root.setCenter(new ScrollPane(content));stage.getScene().setRoot(root);refresh();}
 private void refresh(){content.getChildren().clear();boolean firebase=true;try{FirebaseConfig.getFirestore().collection("users").limit(1).get().get();}catch(Exception e){firebase=false;}GridPane stats=new GridPane();stats.setHgap(12);stats.setVgap(12);stats.add(card("Firebase",""+(firebase?"Operational":"Unavailable")),0,0);stats.add(card("Users",String.valueOf(users.getAllUsers().size())),1,0);stats.add(card("Farmers",String.valueOf(users.getAllFarmers().size())),2,0);stats.add(card("Products",String.valueOf(products.getAllProducts().size())),3,0);stats.add(card("Orders",String.valueOf(orders.getAllOrders().size())),0,1);Button backup=new Button("Create Admin Backup Snapshot");backup.setOnAction(e->backup());VBox box=new VBox(10,new Label("System Overview"),stats,backup,new Label("Recent Admin Audit Logs"));for(Map<String,Object>m:admin.getAll("adminAuditLogs")){box.getChildren().add(new Label(AdminCommon.s(m.get("createdAt"))+" — "+AdminCommon.s(m.get("action"))+" — "+AdminCommon.s(m.get("module"))));}content.getChildren().add(box);}
 private VBox card(String name,String value){VBox b=new VBox(5,new Label(name),new Label(value));b.setPadding(new Insets(14));AdminCommon.card(b);return b;}private void backup(){Map<String,Object>m=new HashMap<>();m.put("status","Completed");m.put("createdAt",new Date());m.put("note","Admin backup snapshot metadata created");String id=admin.create("adminBackups",m);admin.audit("Super Admin","Created Backup Snapshot","System & Data Management",id);AdminCommon.info("Backup","Backup snapshot recorded successfully. This records an admin backup event; it does not export your Firebase database file.");refresh();}
}
